---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    name: jenkins-pv
    type: nfs
spec:
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: "5Gi"
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.1.55.201
    path: "/export/kubernetes/jenkins/jenkins-pv-01"

