---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
  labels:
    name: jenkins-pvc
spec:
  storageClassName: nfs
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      name: jenkins-pv

